# -*- coding: UTF-8 -*-

import addonHandler
from collections import namedtuple

addonHandler.initTranslation()

Smiley = namedtuple('Smiley', 'pattern name chars')
emoticons = [
	# Translators: :) Smile
	Smiley(r'(\s|^)(:([\-]|)([)]{1})(\B|\s|$))', _("smiling smiley"), r':)'),
	# Translators: :( Sad
	Smiley(r'(\s|^)(:([\-]|)([(]{1})\B)', _("sad smiley"), r':('),
	# Translators: :D Laugh
	Smiley(r'(\s|^)(:([\-]|)([D]{1,})\b)', _("Laughing smiley"), r':D'),
	# Translators: :O Surprised
	Smiley(r'(\s|^)(:([\-]|)([O]{1})(\W|\s|$))', _("surprised smiley"), r':O'),
	# Translators: ;) Wink;
	Smiley(r'(\s|^)(;([\-]|)([)D]{1})(\B|\s|$))', _("winking smiley"), r';)'),
	# Translators: ;( Crying
	Smiley(r'(\s|^)(;([\-]|)([(]{1})(\B|\s|$))', _("crying smiley"), r';('),
	# Translators: (:| Sweating
	Smiley(r'(\s|^)\((:[\|])(\B|\s|$)', _("sweating smiley"), r'(:|'),
	# translators:  :|] Robot (a robot head)
	Smiley(r'(\s|^)(:[\|][\]])(\W|\s|$)', _("Robot Smiley"), r':|]'),
	# Translators: :| Speechless
	Smiley(r'(\s|^)(:[\|])(\B|\s|$)', _("speechless smiley"), r':|'),
	# Translators: :* Kiss
	Smiley(r'(\s|^)(:([\-]|)([\*]{1})(\B|\s|$))', _("kiss smiley"), r':*'),
	# Translators: :P Cheeky
	Smiley(r'(\s|^)(:([\-]|)([pP])(\W|\s|$))', _("cheeky smiley"), r':P'),
	# Translators: :$ Blushing
	Smiley(r'(\s|^)(:[\$])(\B|\s|$)', _("blushing smiley"), r':$'),
	# Translators: :^) Wondering
	Smiley(r'(\s|^)(:[\^][\)])(\B|\s|$)', _("wondering smiley"), r':^)'),
	# Translators: |-) Sleepy
	Smiley(r'(\s|^)([\|][\-][\)])(\B|\s|$)', _("sleepy smiley"), r'|-)'),
	# Translators: |-( Dull
	Smiley(r'(\s|^)([\|][\-][\(])(\B|\s|$)', _("dull smiley"), r'|-('),
	# Translators: :x My lips are sealed
	Smiley(r'(\s|^)(:([\-]|)([xX])\b)', _("my lips are sealed smiley"), r':x'),
	# Translators: \o/ Dancing
	Smiley(r'(\s|^)([\\]o[/])(\B|\s|$)', _("dancing smiley"), r'\o/'),
	# Translators: :'( crying a lot smiley
	Smiley(r"(\s|^)([:]['][\(])(\B|\s|$)", _("crying a lot smiley"), r":'("),
	# Translators: >:( Angry
	Smiley(r'(\s|^)(>:[\(])(\B|\s|$)', _("angry smiley"), r'>:('),
	# Translators: :/ Worried
	Smiley(r'(\s|^)(:[/])(\B|\s|$)', _("worried smiley"), r':/'),
	# Translators: <3 Heart
	Smiley(r'(\s|^)<3(\W|\s|$)', _("heart smiley"), r'<3'),
	# Translators:  O:)  O:-) Angel
	Smiley(r'(\s|^)(O:([\-]|)([)])(\W|\s|$))', _("Angel Smiley"), r'O:)'),
	# Translators:  O.o  o.O  Confused
	Smiley(r'(\s|^)[Oo][\.][oO](\B|\s|$)', _("Confused Smiley"), r'O.o'),
	# Translators:   3:-) Devil
	Smiley(r'(\s|^)(3:([\-]|)([\)]))(\B|\s|$)', _("Devil Smiley"), r'3:-)'),
	# Translators:  ^_^ Keke (This smiley is inspired by the Asian style, which is a happy face.)
	Smiley(r'(\s|^)[\^]_[\^](\B|\s|$)', _("Keke Smiley"), r'^_^'),
	# Translators: -_- Bored (This smiley face has its eyes closed and is sporting a very small grin.)
	Smiley(r'(\s|^)[\-]_[\-](\B|\s|$)', _("Bored smiley"), r'-_-'),
	# Translators:  >:O  Upset, angry or shouting...
	Smiley(r'(\s|^)(>:O)(\W|\s|$)', _("Angry Smiley"), r'>:O'),
	# Translators:  :3  Cat (Cat faced smiley with curly lips)
	Smiley(r'(\s|^)(:3)(\W|\s|$)', _("Cat Smiley"), r':3'),
	# Translators: (-.-)ZZZ I’m Sleepy
	Smiley(r'(\s|^)\([-][\.][-]\)ZZZ(\B|\s|$)', _("I am Sleepy smiley"), r'(-.-)ZZZ'),
	# Translators: 8-) Glasses
	Smiley(r'(\s|^)8[-][)](\B|\s|$)', _("glasses smiley"), r'8-)'),
	# Translators: (^^^) shark
	Smiley(r'(\s|^)\([\^]{3}\)(\B|\s|$)', _("shark smiley"), r'(^^^)'),
	# Translators: (worry) Worried
	Smiley(r'(\s|^)\(worry\)(\B|\s|$)', _("worried smiley"), r'(worry)'),
	# Translators:  (cash) Cash
	Smiley(r'(\s|^)\(cash\)(\B|\s|$)', _("cash smiley"), r'(cash)'),
	# Translators: (flex) Muscle
	Smiley(r'(\s|^)\(flex\)(\B|\s|$)', _("muscle smiley"), r'(flex)'),
	# Translators: (beer) Beer
	Smiley(r'(\s|^)\(beer\)(\B|\s|$)', _("beer smiley"), r'(beer)'),
	# Translators: (d) Drink
	Smiley(r'(\s|^)\(d\)(\B|\s|$)', _("drink smiley"), r'(d)'),
	# Translators: (ninja) Ninja
	Smiley(r'(\s|^)\(ninja\)(\B|\s|$)', _("ninja smiley"), r'(ninja)'),
	# Translators: (cool) Cool
	Smiley(r'(\s|^)\(cool\)(\B|\s|$)', _("cool smiley"), r'(cool)'),
	# Translators: (inlove) In Love
	Smiley(r'(\s|^)\(inlove\)(\B|\s|$)', _("in love smiley"), r'(inlove)'),
	# Translators: (yn) Fingers crossed
	Smiley(r'(\s|^)([\(]yn[\)])(\B|\s|$)', _("fingers crossed smiley"), r'(yn)'),
	# Translators: (yawn) Yawn
	Smiley(r'(\s|^)\(yawn\)(\B|\s|$)', _("yawning smiley"), r'(yawn)'),
	# Translators: (puke) Puking
	Smiley(r'(\s|^)\(puke\)(\B|\s|$)', _("puking smiley"), r'(puke)'),
	# Translators: (doh) Doh!
	Smiley(r'(\s|^)\(doh\)(\B|\s|$)', _("doh! smiley"), r'(doh)'),
	# Translators: (angry) Angry
	Smiley(r'(\s|^)\(angry\)(\B|\s|$)', _("angry smiley"), r'(angry)'),
	# Translators: (wasntme) It wasn't me!
	Smiley(r'(\s|^)\(wasntme\)(\B|\s|$)', _("it wasn't me! smiley"), r'(wasntme)'),
	# Translators: (party) Party
	Smiley(r'(\s|^)\(party\)(\B|\s|$)', _("party smiley"), r'(party)'),
	# Translators: (mm) Mmmm...
	Smiley(r'(\s|^)\(mm\)(\B|\s|$)', _("mmmmmm... smiley"), r'(mm)'),
	# Translators: (nerd) Nerdy
	Smiley(r'(\s|^)\(nerd\)(\B|\s|$)', _("nerdy smiley"), r'(nerd)'),
	# Translators: (wave) Hi
	Smiley(r'(\s|^)\(wave\)(\B|\s|$)', _("hi smiley"), r'(wave)'),
	# Translators: (facepalm) Facepalm
	Smiley(r'(\s|^)\(facepalm\)(\B|\s|$)', _("facepalm smiley"), r'(facepalm)'),
	# Translators: (devil) Devil
	Smiley(r'(\s|^)\(devil\)(\B|\s|$)', _("devil smiley"), r'(devil)'),
	# Translators: (angel) Angel
	Smiley(r'(\s|^)\(angel\)(\B|\s|$)', _("angel smiley"), r'(angel)'),
	# Translators: (envy) Envy
	Smiley(r'(\s|^)\(envy\)(\B|\s|$)', _("envy smiley"), r'(envy)'),
	# Translators: (wait) Wait
	Smiley(r'(\s|^)\(wait\)(\B|\s|$)', _("wait smiley"), r'(wait)'),
	# Translators: (hug) Hug
	Smiley(r'(\s|^)\(hug\)(\B|\s|$)', _("hug smiley"), r'(hug)'),
	# Translators: (makeup) Make-up
	Smiley(r'(\s|^)\(makeup\)(\B|\s|$)', _("make-up smiley"), r'(makeup)'),
	# Translators: (chuckle) Giggle
	Smiley(r'(\s|^)\(chuckle\)(\B|\s|$)', _("giggle smiley"), r'(chuckle)'),
	# Translators: (clap) Clapping
	Smiley(r'(\s|^)\(clap\)(\B|\s|$)', _("clapping smiley"), r'(clap)'),
	# Translators: (think) Thinking
	Smiley(r'(\s|^)\(think\)(\B|\s|$)', _("thinking smiley"), r'(think)'),
	# Translators: (bow) Bowing
	Smiley(r'(\s|^)\(bow\)(\B|\s|$)', _("bowing smiley"), r'(bow)'),
	# Translators: (rofl) Rolling on the floor laughing
	Smiley(r'(\s|^)\(rofl\)(\B|\s|$)', _("rolling on the floor laughing! smiley"), r'(rofl)'),
	# Translators: (whew) Relieved
	Smiley(r'(\s|^)\(whew\)(\B|\s|$)', _("relieved smiley"), r'(whew)'),
	# Translators: (happy) Happy
	Smiley(r'(\s|^)\(happy\)(\B|\s|$)', _("happy smiley"), r'(happy)'),
	# Translators: (smirk) Smirking
	Smiley(r'(\s|^)\(smirk\)(\B|\s|$)', _("smirking smiley"), r'(smirk)'),
	# Translators: (nod) Nodding
	Smiley(r'(\s|^)\(nod\)(\B|\s|$)', _("nodding smiley"), r'(nod)'),
	# Translators: (shake) Shake
	Smiley(r'(\s|^)\(shake\)(\B|\s|$)', _("shakeing smiley"), r'(shake)'),
	# Translators: (waiting) Waiting
	Smiley(r'(\s|^)\(waiting\)(\B|\s|$)', _("waiting smiley"), r'(waiting)'),
	# Translators: (emo) Emo;
	Smiley(r'(\s|^)\(emo\)(\B|\s|$)', _("Emo smiley"), r'(emo)'),
	# Translators: (y) Yes
	Smiley(r'(\s|^)\(y\)(\B|\s|$)', _("yes smiley"), r'(y)'),
	# Translators: (n) no;
	Smiley(r'(\s|^)\(n\)(\B|\s|$)', _("no smiley"), r'(n)'),
	# Translators: (handshake) Handshake
	Smiley(r'(\s|^)\(handshake\)(\B|\s|$)', _("handshake smiley"), r'(handshake)'),
	# Translators: (highfive) High five
	Smiley(r'(\s|^)\(highfive\)(\B|\s|$)', _("high five smiley"), r'(highfive)'),
	# Translators: (heart) Heart
	Smiley(r'(\s|^)\(heart\)(\B|\s|$)', _("heart smiley"), r'(heart)'),
	# Translators: (lalala) Lalala;
	Smiley(r'(\s|^)\(lalala\)(\B|\s|$)', _("lalala smiley"), r'(lalala)'),
	# Translators: (heidy) Heidy;
	Smiley(r'(\s|^)\(heidy\)(\B|\s|$)', _("heidy smiley"), r'(heidy)'),
	# Translators: (F) Flower
	Smiley(r'(\s|^)\(F\)(\B|\s|$)', _("flower smiley"), r'(F)'),
	# Translators: (rain) Raining
	Smiley(r'(\s|^)\(rain\)(\B|\s|$)', _("raining smiley"), r'(rain)'),
	# Translators: (sun) Sun
	Smiley(r'(\s|^)\(sun\)(\B|\s|$)', _("sunny smiley"), r'(sun)'),
	# Translators: (tumbleweed) Tumbleweed
	Smiley(r'(\s|^)\(tumbleweed\)(\B|\s|$)', _("tumbleweed smiley"), r'(tumbleweed)'),
	# Translators: (music) Music
	Smiley(r'(\s|^)\(music\)(\B|\s|$)', _("music smiley"), r'(music)'),
	# Translators: (bandit) Bandit
	Smiley(r'(\s|^)\(bandit\)(\B|\s|$)', _("bandit smiley"), r'(bandit)'),
	# Translators: (tmi) Too much information
	Smiley(r'(\s|^)\(tmi\)(\B|\s|$)', _("too much information smiley"), r'(tmi)'),
	# Translators: (coffee) Coffee
	Smiley(r'(\s|^)\(coffee\)(\B|\s|$)', _("coffee smiley"), r'(coffee)'),
	# Translators: (pi) Pizza
	Smiley(r'(\s|^)\(pi\)(\B|\s|$)', _("pizza smiley"), r'(pi)'),
	# Translators: (^) Cake
	Smiley(r'(\s|^)([\(][\^][\)])(\B|\s|$)', _("cake smiley"), r'(^)'),
	# Translators: (*) Star
	Smiley(r'(\s|^)([\(][\*][\)])(\B|\s|$)', _("star smiley"), r'(*)'),
	Smiley(r'¿', _('happy face with open mouth and squinting eyes'), r'¿'),
	Smiley(r'¿', _('happy face with open mouth'), r'¿'),
	Smiley(r'¿', _('happy face with normal eyes'), r'¿'),
	Smiley(r'¿', _('happy face with wide mouth and squinting eyes'), r'¿'),
	Smiley(r'¿', _('white smiling face'), r'¿'),
	Smiley(r'¿', _('white frowning face'), r'¿'),
	Smiley(r'¿', _('winking face'), r'¿'),
	Smiley(r'¿', _('smiling face with heart shaped eyes'), r'¿'),
	Smiley(r'¿', _('face throwing a kiss'), r'¿'),
	Smiley(r'¿', _('kissing face with closed eyes'), r'¿'),
	Smiley(r'¿', _('kissing face with open eyes'), r'¿'),
	Smiley(r'¿', _('kissing face with arched eyes'), r'¿'),
	Smiley(r'¿', _('winking face with stuck out tongue'), r'¿'),
	Smiley(r'¿', _('face with stuck out tongue and eyes tightly closed'), r'¿'),
	Smiley(r'¿', _('face with stuck out tongue and eyes open'), r'¿'),
	Smiley(r'¿', _('flushed face'), r'¿'),
	Smiley(r'¿', _('face with clenched teeth'), r'¿'),
	Smiley(r'¿', _('person frowning'), r'¿'),
	Smiley(r'¿', _('relieved face'), r'¿'),
	Smiley(r'¿', _('unamused face'), r'¿'),
	Smiley(r'¿', _('disappointed face'), r'¿'),
	Smiley(r'¿', _('tired face'), r'¿'),
	Smiley(r'¿', _('crying face'), r'¿'),
	Smiley(r'¿', _('face with tears of joy'), r'¿'),
	Smiley(r'¿', _('loudly crying face'), r'¿'),
	Smiley(r'¿', _('sleepy face'), r'¿'),
	Smiley(r'¿', _('disappointed but relieved face'), r'¿'),
	Smiley(r'¿', _('exasperated face'), r'¿'),
	Smiley(r'¿', _('happy face with teardrop'), r'¿'),
	Smiley(r'¿', _('face with cold sweat'), r'¿'),
	Smiley(r'¿', _('whaling face'), r'¿'),
	Smiley(r'¿', _('whaling face with squinting eyes'), r'¿'),
	Smiley(r'¿', _('fearful face'), r'¿'),
	Smiley(r'¿', _('face screaming in fear'), r'¿'),
	Smiley(r'¿', _('angry face'), r'¿'),
	Smiley(r'¿', _('pouting face'), r'¿'),
	Smiley(r'¿', _('huffing with anger face'), r'¿'),
	Smiley(r'¿', _('confounded face'), r'¿'),
	Smiley(r'¿', _('oddly evil and smiling face'), r'¿'),
	Smiley(r'¿', _('happy face licking lips'), r'¿'),
	Smiley(r'¿', _('face with medical mask'), r'¿'),
	Smiley(r'¿', _('happy face with sunglasses'), r'¿'),
	Smiley(r'¿', _('sleeping face'), r'¿'),
	Smiley(r'¿', _('very astonished face'), r'¿'),
	Smiley(r'¿', _('astonished face'), r'¿'),
	Smiley(r'¿', _('worried face'), r'¿'),
	Smiley(r'¿', _('surprised and dismayed face'), r'¿'),
	Smiley(r'¿', _('anguished face'), r'¿'),
	Smiley(r'¿', _('devil with evil smile'), r'¿'),
	Smiley(r'¿', _('devil'), r'¿'),
	Smiley(r'¿', _('open mouth and surprised face'), r'¿'),
	Smiley(r'¿', _('grimacing face'), r'¿'),
	Smiley(r'¿', _('neutral face'), r'¿'),
	Smiley(r'¿', _('confused face'), r'¿'),
	Smiley(r'¿', _('surprised face'), r'¿'),
	Smiley(r'¿', _('face without mouth'), r'¿'),
	Smiley(r'¿', _('happy face with halo'), r'¿'),
	Smiley(r'¿', _('smirking face'), r'¿'),
	Smiley(r'¿', _('face with straight lined eyes and mouth'), r'¿'),
	Smiley(r'¿', _('chinese man with gua pi mao'), r'¿'),
	Smiley(r'¿', _('asian indian man with turban'), r'¿'),
	Smiley(r'¿', _('police officer'), r'¿'),
	Smiley(r'¿', _('construction worker'), r'¿'),
	Smiley(r'¿', _('guardsman'), r'¿'),
	Smiley(r'¿', _('baby'), r'¿'),
	Smiley(r'¿', _('boys head'), r'¿'),
	Smiley(r'¿', _('girls head'), r'¿'),
	Smiley(r'¿', _('mans head'), r'¿'),
	Smiley(r'¿', _('womans head'), r'¿'),
	Smiley(r'¿', _('older man'), r'¿'),
	Smiley(r'¿', _('older woman'), r'¿'),
	Smiley(r'¿', _('western person with blonde hair'), r'¿'),
	Smiley(r'¿', _('angel'), r'¿'),
	Smiley(r'¿', _('princess'), r'¿'),
	Smiley(r'¿', _('happy cat face'), r'¿'),
	Smiley(r'¿', _('grinning cat face'), r'¿'),
	Smiley(r'¿', _('happy cat face with heart shaped eyes'), r'¿'),
	Smiley(r'¿', _('kissing cat face with closed eyes'), r'¿'),
	Smiley(r'¿', _('smirking cat face'), r'¿'),
	Smiley(r'¿', _('screaming in fear cat face'), r'¿'),
	Smiley(r'¿', _('crying cat face'), r'¿'),
	Smiley(r'¿', _('laughing with tears cat face'), r'¿'),
	Smiley(r'¿', _('unhappy sideways cat face'), r'¿'),
	Smiley(r'¿', _('japanese ogre mask'), r'¿'),
	Smiley(r'¿', _('japanese goblin mask'), r'¿'),
	Smiley(r'¿', _('see no evil monkey'), r'¿'),
	Smiley(r'¿', _('hear no evil monkey'), r'¿'),
	Smiley(r'¿', _('speak no evil monkey'), r'¿'),
	Smiley(r'¿', _('skull'), r'¿'),
	Smiley(r'¿', _('extraterrestrial alien'), r'¿'),
	Smiley(r'¿', _('smiling pile of poo'), r'¿'),
	Smiley(r'¿', _('fire'), r'¿'),
	Smiley(r'¿', _('three shining stars'), r'¿'),
	Smiley(r'¿', _('glowing star'), r'¿'),
	Smiley(r'¿', _('shooting star'), r'¿'),
	Smiley(r'¿', _('explosion'), r'¿'),
	Smiley(r'¿', _('anger symbol'), r'¿'),
	Smiley(r'¿', _('drip'), r'¿'),
	Smiley(r'¿', _('water droplet'), r'¿'),
	Smiley(r'¿', _('sleeping symbol'), r'¿'),
	Smiley(r'¿', _('ear'), r'¿'),
	Smiley(r'¿', _('eyes'), r'¿'),
	Smiley(r'¿', _('nose'), r'¿'),
	Smiley(r'¿', _('tongue'), r'¿'),
	Smiley(r'¿', _('lips'), r'¿'),
	Smiley(r'¿', _('thumbs up symbol'), r'¿'),
	Smiley(r'¿', _('thumbs down symbol'), r'¿'),
	Smiley(r'¿', _('ok hand sign'), r'¿'),
	Smiley(r'¿', _('fisted hand'), r'¿'),
	Smiley(r'¿', _('raised fist'), r'¿'),
	Smiley(r'¿', _('hand making peace sign'), r'¿'),
	Smiley(r'¿', _('waving hand sign'), r'¿'),
	Smiley(r'¿', _('raised open hand'), r'¿'),
	Smiley(r'¿', _('open hands'), r'¿'),
	Smiley(r'¿', _('white up pointing backhand index'), r'¿'),
	Smiley(r'¿', _('white down pointing backhand index'), r'¿'),
	Smiley(r'¿', _('white right pointing backhand index'), r'¿'),
	Smiley(r'¿', _('white left pointing backhand index'), r'¿'),
	Smiley(r'¿', _('person raising both hands in cheers'), r'¿'),
	Smiley(r'¿', _('person with folded hands'), r'¿'),
	Smiley(r'¿', _('hand with index finger pointing up'), r'¿'),
	Smiley(r'¿', _('clapping hands'), r'¿'),
	Smiley(r'¿', _('flexed biceps'), r'¿'),
	Smiley(r'¿', _('pedestrian'), r'¿'),
	Smiley(r'¿', _('runner'), r'¿'),
	Smiley(r'¿', _('dancer'), r'¿'),
	Smiley(r'¿', _('man and woman holding hands'), r'¿'),
	Smiley(r'¿', _('family of three'), r'¿'),
	Smiley(r'¿', _('two men holding hands'), r'¿'),
	Smiley(r'¿', _('two woman holding hands'), r'¿'),
	Smiley(r'¿', _('man and woman about to kiss'), r'¿'),
	Smiley(r'¿', _('couple with heart'), r'¿'),
	Smiley(r'¿', _('woman with bunny ears'), r'¿'),
	Smiley(r'¿', _('person making ok gesture'), r'¿'),
	Smiley(r'¿', _('person making no good gesture'), r'¿'),
	Smiley(r'¿', _('customer service person'), r'¿'),
	Smiley(r'¿', _('happy woman raising a hand'), r'¿'),
	Smiley(r'¿', _('head massage'), r'¿'),
	Smiley(r'¿', _('haircut'), r'¿'),
	Smiley(r'¿', _('pink manicure'), r'¿'),
	Smiley(r'¿', _('woman wearing a bridal vale'), r'¿'),
	Smiley(r'¿', _('woman staring straight ahead'), r'¿'),
	Smiley(r'¿', _('woman with downcast face'), r'¿'),
	Smiley(r'¿', _('person bowing deeply'), r'¿'),
	Smiley(r'¿', _('top hat'), r'¿'),
	Smiley(r'¿', _('crown'), r'¿'),
	Smiley(r'¿', _('womans hat'), r'¿'),
	Smiley(r'¿', _('athletic shoe'), r'¿'),
	Smiley(r'¿', _('brown sneaker'), r'¿'),
	Smiley(r'¿', _('womans sandal'), r'¿'),
	Smiley(r'¿', _('high heal shoe'), r'¿'),
	Smiley(r'¿', _('womans boots'), r'¿'),
	Smiley(r'¿', _('short sleeved polo shirt'), r'¿'),
	Smiley(r'¿', _('neck tie'), r'¿'),
	Smiley(r'¿', _('blouse'), r'¿'),
	Smiley(r'¿', _('dress'), r'¿'),
	Smiley(r'¿', _('womans tank top with sash'), r'¿'),
	Smiley(r'¿', _('denim jeans'), r'¿'),
	Smiley(r'¿', _('kimono'), r'¿'),
	Smiley(r'¿', _('bikini'), r'¿'),
	Smiley(r'¿', _('briefcase'), r'¿'),
	Smiley(r'¿', _('handbag'), r'¿'),
	Smiley(r'¿', _('tan purse'), r'¿'),
	Smiley(r'¿', _('pink purse'), r'¿'),
	Smiley(r'¿', _('eye glasses'), r'¿'),
	Smiley(r'¿', _('ribbon'), r'¿'),
	Smiley(r'¿', _('closed umbrella'), r'¿'),
	Smiley(r'¿', _('lipstick'), r'¿'),
	Smiley(r'¿', _('yellow heart'), r'¿'),
	Smiley(r'¿', _('blue heart'), r'¿'),
	Smiley(r'¿', _('purple heart'), r'¿'),
	Smiley(r'¿', _('green heart'), r'¿'),
	Smiley(r'¿', _('red heart'), r'¿'),
	Smiley(r'¿', _('broken heart'), r'¿'),
	Smiley(r'¿', _('pulsating heart'), r'¿'),
	Smiley(r'¿', _('beating heart'), r'¿'),
	Smiley(r'¿', _('two hearts'), r'¿'),
	Smiley(r'¿', _('heart with stars'), r'¿'),
	Smiley(r'¿', _('two circling hearts'), r'¿'),
	Smiley(r'¿', _('heart with arrow'), r'¿'),
	Smiley(r'¿', _('envelope sealed with kiss'), r'¿'),
	Smiley(r'¿', _('kiss mark'), r'¿'),
	Smiley(r'¿', _('ring'), r'¿'),
	Smiley(r'¿', _('gem stone'), r'¿'),
	Smiley(r'¿', _('silhouetted person'), r'¿'),
	Smiley(r'¿', _('silhouetted two people'), r'¿'),
	Smiley(r'¿', _('speech bubble'), r'¿'),
	Smiley(r'¿', _('footprints'), r'¿'),
	Smiley(r'¿', _('thought bubble'), r'¿'),
	Smiley(r'¿', _('dog face'), r'¿'),
	Smiley(r'¿', _('wolf face'), r'¿'),
	Smiley(r'¿', _('cat face'), r'¿'),
	Smiley(r'¿', _('mouse face'), r'¿'),
	Smiley(r'¿', _('hamster face'), r'¿'),
	Smiley(r'¿', _('rabbit face'), r'¿'),
	Smiley(r'¿', _('frog face'), r'¿'),
	Smiley(r'¿', _('tiger face'), r'¿'),
	Smiley(r'¿', _('koala face'), r'¿'),
	Smiley(r'¿', _('bear face'), r'¿'),
	Smiley(r'¿', _('pig face'), r'¿'),
	Smiley(r'¿', _('pig nose'), r'¿'),
	Smiley(r'¿', _('cow face'), r'¿'),
	Smiley(r'¿', _('boar'), r'¿'),
	Smiley(r'¿', _('monkey face'), r'¿'),
	Smiley(r'¿', _('monkey'), r'¿'),
	Smiley(r'¿', _('horse face'), r'¿'),
	Smiley(r'¿', _('sheep'), r'¿'),
	Smiley(r'¿', _('elephant'), r'¿'),
	Smiley(r'¿', _('panda face'), r'¿'),
	Smiley(r'¿', _('penguin'), r'¿'),
	Smiley(r'¿', _('bird'), r'¿'),
	Smiley(r'¿', _('baby chick'), r'¿'),
	Smiley(r'¿', _('standing baby chick'), r'¿'),
	Smiley(r'¿', _('recently hatched chick still in shell'), r'¿'),
	Smiley(r'¿', _('chicken'), r'¿'),
	Smiley(r'¿', _('snake'), r'¿'),
	Smiley(r'¿', _('turtle'), r'¿'),
	Smiley(r'¿', _('caterpillar'), r'¿'),
	Smiley(r'¿', _('honey bee'), r'¿'),
	Smiley(r'¿', _('ant'), r'¿'),
	Smiley(r'¿', _('ladybug'), r'¿'),
	Smiley(r'¿', _('snail'), r'¿'),
	Smiley(r'¿', _('octopus'), r'¿'),
	Smiley(r'¿', _('seashell'), r'¿'),
	Smiley(r'¿', _('tropical fish'), r'¿'),
	Smiley(r'¿', _('fish'), r'¿'),
	Smiley(r'¿', _('dolphin'), r'¿'),
	Smiley(r'¿', _('spouting wale'), r'¿'),
	Smiley(r'¿', _('sperm wale'), r'¿'),
	Smiley(r'¿', _('cow'), r'¿'),
	Smiley(r'¿', _('ram'), r'¿'),
	Smiley(r'¿', _('rat'), r'¿'),
	Smiley(r'¿', _('water buffalo'), r'¿'),
	Smiley(r'¿', _('tiger'), r'¿'),
	Smiley(r'¿', _('rabbit'), r'¿'),
	Smiley(r'¿', _('dragon'), r'¿'),
	Smiley(r'¿', _('galloping horse with saddle'), r'¿'),
	Smiley(r'¿', _('goat'), r'¿'),
	Smiley(r'¿', _('rooster'), r'¿'),
	Smiley(r'¿', _('dog'), r'¿'),
	Smiley(r'¿', _('pig'), r'¿'),
	Smiley(r'¿', _('mouse'), r'¿'),
	Smiley(r'¿', _('ox'), r'¿'),
	Smiley(r'¿', _('dragon face'), r'¿'),
	Smiley(r'¿', _('blowfish'), r'¿'),
	Smiley(r'¿', _('crocodile'), r'¿'),
	Smiley(r'¿', _('camel'), r'¿'),
	Smiley(r'¿', _('one humped camel'), r'¿'),
	Smiley(r'¿', _('leopard'), r'¿'),
	Smiley(r'¿', _('house cat'), r'¿'),
	Smiley(r'¿', _('poodle'), r'¿'),
	Smiley(r'¿', _('paw prints'), r'¿'),
	Smiley(r'¿', _('flower bouquet'), r'¿'),
	Smiley(r'¿', _('cherry blossom'), r'¿'),
	Smiley(r'¿', _('tulip'), r'¿'),
	Smiley(r'¿', _('four leaf clover'), r'¿'),
	Smiley(r'¿', _('rose'), r'¿'),
	Smiley(r'¿', _('sunflower'), r'¿'),
	Smiley(r'¿', _('hibiscus'), r'¿'),
	Smiley(r'¿', _('maple leaf'), r'¿'),
	Smiley(r'¿', _('leaves fluttering in wind'), r'¿'),
	Smiley(r'¿', _('fallen leaves'), r'¿'),
	Smiley(r'¿', _('branch with leaves'), r'¿'),
	Smiley(r'¿', _('ear of rice'), r'¿'),
	Smiley(r'¿', _('mushroom'), r'¿'),
	Smiley(r'¿', _('cactus'), r'¿'),
	Smiley(r'¿', _('palm tree'), r'¿'),
	Smiley(r'¿', _('pine tree'), r'¿'),
	Smiley(r'¿', _('leafy tree'), r'¿'),
	Smiley(r'¿', _('chestnut'), r'¿'),
	Smiley(r'¿', _('sapling plant'), r'¿'),
	Smiley(r'¿', _('flower'), r'¿'),
	Smiley(r'¿', _('globe with meridians'), r'¿'),
	Smiley(r'¿', _('sun with face'), r'¿'),
	Smiley(r'¿', _('full moon with face'), r'¿'),
	Smiley(r'¿', _('new moon with face'), r'¿'),
	Smiley(r'¿', _('new moon'), r'¿'),
	Smiley(r'¿', _('waxing crescent moon'), r'¿'),
	Smiley(r'¿', _('first quarter moon'), r'¿'),
	Smiley(r'¿', _('waxing gibbous moon'), r'¿'),
	Smiley(r'¿', _('full moon'), r'¿'),
	Smiley(r'¿', _('waning gibbous moon'), r'¿'),
	Smiley(r'¿', _('last quarter moon'), r'¿'),
	Smiley(r'¿', _('waning crescent moon'), r'¿'),
	Smiley(r'¿', _('last quarter moon with face'), r'¿'),
	Smiley(r'¿', _('first quarter moon with face'), r'¿'),
	Smiley(r'¿', _('crescent shaped moon'), r'¿'),
	Smiley(r'¿', _('globe featuring europe and africa'), r'¿'),
	Smiley(r'¿', _('globe featuring north and south america'), r'¿'),
	Smiley(r'¿', _('globe featuring asia and australia'), r'¿'),
	Smiley(r'¿', _('volcano erupting pictorial card'), r'¿'),
	Smiley(r'¿', _('milky way pictorial card'), r'¿'),
	Smiley(r'¿', _('shooting star pictorial card'), r'¿'),
	Smiley(r'¿', _('star emoji'), r'¿'),
	Smiley(r'¿', _('sun with rays'), r'¿'),
	Smiley(r'¿', _('sun behind cloud'), r'¿'),
	Smiley(r'¿', _('cloud'), r'¿'),
	Smiley(r'¿', _('high voltage symbol'), r'¿'),
	Smiley(r'¿', _('umbrella with raindrops'), r'¿'),
	Smiley(r'¿', _('snowflake'), r'¿'),
	Smiley(r'¿', _('snowman'), r'¿'),
	Smiley(r'¿', _('typhoon'), r'¿'),
	Smiley(r'¿', _('fog'), r'¿'),
	Smiley(r'¿', _('rainbow'), r'¿'),
	Smiley(r'¿', _('tidal wave'), r'¿'),
	Smiley(r'¿', _('bamboo decoration'), r'¿'),
	Smiley(r'¿', _('heart with ribbon'), r'¿'),
	Smiley(r'¿', _('japanese dolls'), r'¿'),
	Smiley(r'¿', _('backpack'), r'¿'),
	Smiley(r'¿', _('graduation cap'), r'¿'),
	Smiley(r'¿', _('carp streamer'), r'¿'),
	Smiley(r'¿', _('fireworks'), r'¿'),
	Smiley(r'¿', _('firework sparkler'), r'¿'),
	Smiley(r'¿', _('wind chimes'), r'¿'),
	Smiley(r'¿', _('moon viewing ceremony'), r'¿'),
	Smiley(r'¿', _('jack o lantern'), r'¿'),
	Smiley(r'¿', _('ghost'), r'¿'),
	Smiley(r'¿', _('santa claus'), r'¿'),
	Smiley(r'¿', _('christmas tree'), r'¿'),
	Smiley(r'¿', _('wrapped present'), r'¿'),
	Smiley(r'¿', _('tanabata tree'), r'¿'),
	Smiley(r'¿', _('party popper'), r'¿'),
	Smiley(r'¿', _('confetti ball'), r'¿'),
	Smiley(r'¿', _('balloon'), r'¿'),
	Smiley(r'¿', _('crossed flags'), r'¿'),
	Smiley(r'¿', _('crystal ball'), r'¿'),
	Smiley(r'¿', _('movie camera'), r'¿'),
	Smiley(r'¿', _('camera'), r'¿'),
	Smiley(r'¿', _('video camera'), r'¿'),
	Smiley(r'¿', _('video cassette'), r'¿'),
	Smiley(r'¿', _('cd'), r'¿'),
	Smiley(r'¿', _('dvd'), r'¿'),
	Smiley(r'¿', _('minidisc'), r'¿'),
	Smiley(r'¿', _('floppy disk'), r'¿'),
	Smiley(r'¿', _('computer'), r'¿'),
	Smiley(r'¿', _('cell phone'), r'¿'),
	Smiley(r'¿', _('telephone'), r'¿'),
	Smiley(r'¿', _('telephone receiver'), r'¿'),
	Smiley(r'¿', _('pager'), r'¿'),
	Smiley(r'¿', _('fax machine'), r'¿'),
	Smiley(r'¿', _('satellite antenna'), r'¿'),
	Smiley(r'¿', _('tv'), r'¿'),
	Smiley(r'¿', _('radio'), r'¿'),
	Smiley(r'¿', _('speaker with three sound waves'), r'¿'),
	Smiley(r'¿', _('speaker with one sound wave'), r'¿'),
	Smiley(r'¿', _('speaker'), r'¿'),
	Smiley(r'¿', _('speaker with cancelation stroke'), r'¿'),
	Smiley(r'¿', _('bell'), r'¿'),
	Smiley(r'¿', _('bell with cancelation stroke'), r'¿'),
	Smiley(r'¿', _('public address loudspeaker'), r'¿'),
	Smiley(r'¿', _('cheering megaphone'), r'¿'),
	Smiley(r'¿', _('hour glass with flowing sand'), r'¿'),
	Smiley(r'¿', _('hour glass'), r'¿'),
	Smiley(r'¿', _('alarm clock'), r'¿'),
	Smiley(r'¿', _('watch'), r'¿'),
	Smiley(r'¿', _('open lock'), r'¿'),
	Smiley(r'¿', _('closed lock'), r'¿'),
	Smiley(r'¿', _('lock with ink pen'), r'¿'),
	Smiley(r'¿', _('closed lock with key'), r'¿'),
	Smiley(r'¿', _('key'), r'¿'),
	Smiley(r'¿', _('right pointing magnifying glass'), r'¿'),
	Smiley(r'¿', _('electric light bulb'), r'¿'),
	Smiley(r'¿', _('flashlight'), r'¿'),
	Smiley(r'¿', _('high brightness symbol'), r'¿'),
	Smiley(r'¿', _('low brightness symbol'), r'¿'),
	Smiley(r'¿', _('electric plug'), r'¿'),
	Smiley(r'¿', _('battery'), r'¿'),
	Smiley(r'¿', _('left pointing magnifying glass'), r'¿'),
	Smiley(r'¿', _('bathtub with shower head'), r'¿'),
	Smiley(r'¿', _('bath'), r'¿'),
	Smiley(r'¿', _('shower head with water flowing'), r'¿'),
	Smiley(r'¿', _('toilet'), r'¿'),
	Smiley(r'¿', _('wrench'), r'¿'),
	Smiley(r'¿', _('nut and bolt'), r'¿'),
	Smiley(r'¿', _('hammer'), r'¿'),
	Smiley(r'¿', _('door'), r'¿'),
	Smiley(r'¿', _('smoking sign'), r'¿'),
	Smiley(r'¿', _('bomb'), r'¿'),
	Smiley(r'¿', _('pistol'), r'¿'),
	Smiley(r'¿', _('butcher knife'), r'¿'),
	Smiley(r'¿', _('pill'), r'¿'),
	Smiley(r'¿', _('syringe'), r'¿'),
	Smiley(r'¿', _('money bag'), r'¿'),
	Smiley(r'¿', _('bank note with yen sign'), r'¿'),
	Smiley(r'¿', _('bank note with u s dollar sign'), r'¿'),
	Smiley(r'¿', _('bank note with brittish pound sign'), r'¿'),
	Smiley(r'¿', _('bank note with euro sign'), r'¿'),
	Smiley(r'¿', _('back of a credit card'), r'¿'),
	Smiley(r'¿', _('wad of money with wings'), r'¿'),
	Smiley(r'¿', _('arrow at left pointing to cell phone at right'), r'¿'),
	Smiley(r'¿', _('email symbol'), r'¿'),
	Smiley(r'¿', _('inbox tray'), r'¿'),
	Smiley(r'¿', _('outbox tray'), r'¿'),
	Smiley(r'¿', _('envelope'), r'¿'),
	Smiley(r'¿', _('arrow pointing down at envelope'), r'¿'),
	Smiley(r'¿', _('incoming envelope'), r'¿'),
	Smiley(r'¿', _('postal horn'), r'¿'),
	Smiley(r'¿', _('closed mailbox with raised flag'), r'¿'),
	Smiley(r'¿', _('closed mailbox with lowered flag'), r'¿'),
	Smiley(r'¿', _('open mailbox with raised flag'), r'¿'),
	Smiley(r'¿', _('open mailbox with lowered flag'), r'¿'),
	Smiley(r'¿', _('postbox'), r'¿'),
	Smiley(r'¿', _('mail parcel'), r'¿'),
	Smiley(r'¿', _('memo'), r'¿'),
	Smiley(r'¿', _('page facing up'), r'¿'),
	Smiley(r'¿', _('page with curl'), r'¿'),
	Smiley(r'¿', _('pages with bookmark tabs'), r'¿'),
	Smiley(r'¿', _('bar chart'), r'¿'),
	Smiley(r'¿', _('chart with upwards trend'), r'¿'),
	Smiley(r'¿', _('chart with downwards trend'), r'¿'),
	Smiley(r'¿', _('speech from the apple crazy ones ad on a parchment scroll'), r'¿'),
	Smiley(r'¿', _('clipboard'), r'¿'),
	Smiley(r'¿', _('calendar'), r'¿'),
	Smiley(r'¿', _('tear off calendar'), r'¿'),
	Smiley(r'¿', _('business card index'), r'¿'),
	Smiley(r'¿', _('closed file folder'), r'¿'),
	Smiley(r'¿', _('open file folder'), r'¿'),
	Smiley(r'¿', _('scissors'), r'¿'),
	Smiley(r'¿', _('pushpin'), r'¿'),
	Smiley(r'¿', _('paper clip'), r'¿'),
	Smiley(r'¿', _('tip from old style ink pen'), r'¿'),
	Smiley(r'¿', _('pencil'), r'¿'),
	Smiley(r'¿', _('straight ruler'), r'¿'),
	Smiley(r'¿', _('triangular ruler'), r'¿'),
	Smiley(r'¿', _('closed red book reading volume one by john appleseed'), r'¿'),
	Smiley(r'¿', _('closed green book reading volume two by john appleseed'), r'¿'),
	Smiley(r'¿', _('closed blue book reading volume three by john appleseed'), r'¿'),
	Smiley(r'¿', _('closed orange book reading volume four by john appleseed'), r'¿'),
	Smiley(r'¿', _('black and white dotted notebook labeled notes'), r'¿'),
	Smiley(r'¿', _('notebook with decorative cover'), r'¿'),
	Smiley(r'¿', _('yellow ledger'), r'¿'),
	Smiley(r'¿', _('stack of three books'), r'¿'),
	Smiley(r'¿', _('open book'), r'¿'),
	Smiley(r'¿', _('bookmark'), r'¿'),
	Smiley(r'¿', _('name badge'), r'¿'),
	Smiley(r'¿', _('microscope'), r'¿'),
	Smiley(r'¿', _('telescope'), r'¿'),
	Smiley(r'¿', _('newspaper'), r'¿'),
	Smiley(r'¿', _('painters palette'), r'¿'),
	Smiley(r'¿', _('clapboard'), r'¿'),
	Smiley(r'¿', _('microphone'), r'¿'),
	Smiley(r'¿', _('headphone'), r'¿'),
	Smiley(r'¿', _('musical score'), r'¿'),
	Smiley(r'¿', _('musical note'), r'¿'),
	Smiley(r'¿', _('multiple musical notes'), r'¿'),
	Smiley(r'¿', _('musical keyboard with 7 keys'), r'¿'),
	Smiley(r'¿', _('violin'), r'¿'),
	Smiley(r'¿', _('trumpet'), r'¿'),
	Smiley(r'¿', _('saxophone'), r'¿'),
	Smiley(r'¿', _('guitar'), r'¿'),
	Smiley(r'¿', _('alien monster'), r'¿'),
	Smiley(r'¿', _('video game controller'), r'¿'),
	Smiley(r'¿', _('black joker playing card'), r'¿'),
	Smiley(r'¿', _('flower playing cards'), r'¿'),
	Smiley(r'¿', _('Mahjong Tile Red Dragon'), r'¿'),
	Smiley(r'¿', _('board game die'), r'¿'),
	Smiley(r'¿', _('direct hit or bullseye'), r'¿'),
	Smiley(r'¿', _('american football'), r'¿'),
	Smiley(r'¿', _('basketball and hoop'), r'¿'),
	Smiley(r'¿', _('soccer ball'), r'¿'),
	Smiley(r'¿', _('baseball'), r'¿'),
	Smiley(r'¿', _('tennis racket and ball'), r'¿'),
	Smiley(r'¿', _('billiards cue ball'), r'¿'),
	Smiley(r'¿', _('rugby football'), r'¿'),
	Smiley(r'¿', _('bowling ball and pins'), r'¿'),
	Smiley(r'¿', _('golf flag in hole'), r'¿'),
	Smiley(r'¿', _('mountain bicyclist'), r'¿'),
	Smiley(r'¿', _('bicyclist'), r'¿'),
	Smiley(r'¿', _('checkered flag'), r'¿'),
	Smiley(r'¿', _('galloping horse with sadel and jockey'), r'¿'),
	Smiley(r'¿', _('trophy'), r'¿'),
	Smiley(r'¿', _('ski and ski boot'), r'¿'),
	Smiley(r'¿', _('snowboarder'), r'¿'),
	Smiley(r'¿', _('swimmer'), r'¿'),
	Smiley(r'¿', _('surfer'), r'¿'),
	Smiley(r'¿', _('fishing pole and fish'), r'¿'),
	Smiley(r'¿', _('hot beverage'), r'¿'),
	Smiley(r'¿', _('teacup without handle'), r'¿'),
	Smiley(r'¿', _('sake bottle and cup'), r'¿'),
	Smiley(r'¿', _('baby bottle'), r'¿'),
	Smiley(r'¿', _('beer mug'), r'¿'),
	Smiley(r'¿', _('clinking beer mugs'), r'¿'),
	Smiley(r'¿', _('cocktail glass'), r'¿'),
	Smiley(r'¿', _('orange tropical drink'), r'¿'),
	Smiley(r'¿', _('wine glass'), r'¿'),
	Smiley(r'¿', _('fork and knife'), r'¿'),
	Smiley(r'¿', _('slice of pizza'), r'¿'),
	Smiley(r'¿', _('hamburger'), r'¿'),
	Smiley(r'¿', _('french fries'), r'¿'),
	Smiley(r'¿', _('turkey leg'), r'¿'),
	Smiley(r'¿', _('meat on bone'), r'¿'),
	Smiley(r'¿', _('spaghetti'), r'¿'),
	Smiley(r'¿', _('curry and rice'), r'¿'),
	Smiley(r'¿', _('fried shrimp'), r'¿'),
	Smiley(r'¿', _('bento box'), r'¿'),
	Smiley(r'¿', _('sushi'), r'¿'),
	Smiley(r'¿', _('fish cake with swirl design'), r'¿'),
	Smiley(r'¿', _('rice ball'), r'¿'),
	Smiley(r'¿', _('rice cracker'), r'¿'),
	Smiley(r'¿', _('cooked rice'), r'¿'),
	Smiley(r'¿', _('steaming bowl of food'), r'¿'),
	Smiley(r'¿', _('pot of food'), r'¿'),
	Smiley(r'¿', _('oden on skewer'), r'¿'),
	Smiley(r'¿', _('dango dessert stick'), r'¿'),
	Smiley(r'¿', _('pan with sunny side up egg'), r'¿'),
	Smiley(r'¿', _('bread'), r'¿'),
	Smiley(r'¿', _('doughnut'), r'¿'),
	Smiley(r'¿', _('custard'), r'¿'),
	Smiley(r'¿', _('soft serve ice cream'), r'¿'),
	Smiley(r'¿', _('ice cream'), r'¿'),
	Smiley(r'¿', _('shaved ice'), r'¿'),
	Smiley(r'¿', _('cake with three candles and strawberries'), r'¿'),
	Smiley(r'¿', _('slice of shortcake'), r'¿'),
	Smiley(r'¿', _('cookie'), r'¿'),
	Smiley(r'¿', _('chocolate bar'), r'¿'),
	Smiley(r'¿', _('wrapped candy'), r'¿'),
	Smiley(r'¿', _('swirly lollipop'), r'¿'),
	Smiley(r'¿', _('honey pot'), r'¿'),
	Smiley(r'¿', _('red apple'), r'¿'),
	Smiley(r'¿', _('green apple'), r'¿'),
	Smiley(r'¿', _('tangerine'), r'¿'),
	Smiley(r'¿', _('lemon'), r'¿'),
	Smiley(r'¿', _('cherries'), r'¿'),
	Smiley(r'¿', _('grapes'), r'¿'),
	Smiley(r'¿', _('watermelon'), r'¿'),
	Smiley(r'¿', _('strawberry'), r'¿'),
	Smiley(r'¿', _('peach'), r'¿'),
	Smiley(r'¿', _('melon'), r'¿'),
	Smiley(r'¿', _('banana'), r'¿'),
	Smiley(r'¿', _('pear'), r'¿'),
	Smiley(r'¿', _('pineapple'), r'¿'),
	Smiley(r'¿', _('roasted sweet potato'), r'¿'),
	Smiley(r'¿', _('eggplant'), r'¿'),
	Smiley(r'¿', _('tomato'), r'¿'),
	Smiley(r'¿', _('ear of corn'), r'¿'),
	Smiley(r'¿', _('house with yard'), r'¿'),
	Smiley(r'¿', _('house with garden'), r'¿'),
	Smiley(r'¿', _('school'), r'¿'),
	Smiley(r'¿', _('office building'), r'¿'),
	Smiley(r'¿', _('japanese post office'), r'¿'),
	Smiley(r'¿', _('hospital'), r'¿'),
	Smiley(r'¿', _('bank'), r'¿'),
	Smiley(r'¿', _('convenience store'), r'¿'),
	Smiley(r'¿', _('hotel paid by the hour'), r'¿'),
	Smiley(r'¿', _('hotel'), r'¿'),
	Smiley(r'¿', _('church with love heart above it'), r'¿'),
	Smiley(r'¿', _('church'), r'¿'),
	Smiley(r'¿', _('department store'), r'¿'),
	Smiley(r'¿', _('european post office'), r'¿'),
	Smiley(r'¿', _('sunset over buildings'), r'¿'),
	Smiley(r'¿', _('cityscape at dusk'), r'¿'),
	Smiley(r'¿', _('japanese castle'), r'¿'),
	Smiley(r'¿', _('european castle'), r'¿'),
	Smiley(r'¿', _('tent at night'), r'¿'),
	Smiley(r'¿', _('factory'), r'¿'),
	Smiley(r'¿', _('tokyo tower'), r'¿'),
	Smiley(r'¿', _('silhouette of japan'), r'¿'),
	Smiley(r'¿', _('mount fuji'), r'¿'),
	Smiley(r'¿', _('sunrise over mountains'), r'¿'),
	Smiley(r'¿', _('sunrise'), r'¿'),
	Smiley(r'¿', _('cityscape at night'), r'¿'),
	Smiley(r'¿', _('statue of liberty'), r'¿'),
	Smiley(r'¿', _('bridge at night'), r'¿'),
	Smiley(r'¿', _('carousel horse'), r'¿'),
	Smiley(r'¿', _('ferris wheel'), r'¿'),
	Smiley(r'¿', _('fountain'), r'¿'),
	Smiley(r'¿', _('roller coaster'), r'¿'),
	Smiley(r'¿', _('ship'), r'¿'),
	Smiley(r'¿', _('sailboat'), r'¿'),
	Smiley(r'¿', _('speedboat'), r'¿'),
	Smiley(r'¿', _('rowboat'), r'¿'),
	Smiley(r'¿', _('anchor'), r'¿'),
	Smiley(r'¿', _('rocket'), r'¿'),
	Smiley(r'¿', _('airplane'), r'¿'),
	Smiley(r'¿', _('airplane seat'), r'¿'),
	Smiley(r'¿', _('helicopter'), r'¿'),
	Smiley(r'¿', _('steam locomotive'), r'¿'),
	Smiley(r'¿', _('train'), r'¿'),
	Smiley(r'¿', _('subway station'), r'¿'),
	Smiley(r'¿', _('mountain railway'), r'¿'),
	Smiley(r'¿', _('frontfacing train'), r'¿'),
	Smiley(r'¿', _('high speed train'), r'¿'),
	Smiley(r'¿', _('high speed train with bullet nose'), r'¿'),
	Smiley(r'¿', _('light rail'), r'¿'),
	Smiley(r'¿', _('subway sign'), r'¿'),
	Smiley(r'¿', _('monorail'), r'¿'),
	Smiley(r'¿', _('tram car'), r'¿'),
	Smiley(r'¿', _('railway car'), r'¿'),
	Smiley(r'¿', _('trolley'), r'¿'),
	Smiley(r'¿', _('bus'), r'¿'),
	Smiley(r'¿', _('oncoming bus'), r'¿'),
	Smiley(r'¿', _('Sport Utility Vehicle'), r'¿'),
	Smiley(r'¿', _('oncoming car'), r'¿'),
	Smiley(r'¿', _('car'), r'¿'),
	Smiley(r'¿', _('taxi'), r'¿'),
	Smiley(r'¿', _('oncoming taxi'), r'¿'),
	Smiley(r'¿', _('articulated lorry'), r'¿'),
	Smiley(r'¿', _('delivery truck'), r'¿'),
	Smiley(r'¿', _('police cars revolving light'), r'¿'),
	Smiley(r'¿', _('police car'), r'¿'),
	Smiley(r'¿', _('oncoming police car'), r'¿'),
	Smiley(r'¿', _('fire engine'), r'¿'),
	Smiley(r'¿', _('ambulance'), r'¿'),
	Smiley(r'¿', _('minibus'), r'¿'),
	Smiley(r'¿', _('bicycle'), r'¿'),
	Smiley(r'¿', _('aerial tramway'), r'¿'),
	Smiley(r'¿', _('suspension railway'), r'¿'),
	Smiley(r'¿', _('mountain cableway'), r'¿'),
	Smiley(r'¿', _('tractor'), r'¿'),
	Smiley(r'¿', _('barber pole'), r'¿'),
	Smiley(r'¿', _('bus stop'), r'¿'),
	Smiley(r'¿', _('ticket'), r'¿'),
	Smiley(r'¿', _('vertical traffic light'), r'¿'),
	Smiley(r'¿', _('horizontal traffic light'), r'¿'),
	Smiley(r'¿', _('hazard sign'), r'¿'),
	Smiley(r'¿', _('construction sign'), r'¿'),
	Smiley(r'¿', _('japanese symbol for beginner'), r'¿'),
	Smiley(r'¿', _('gas pump'), r'¿'),
	Smiley(r'¿', _('Izakaya Lantern'), r'¿'),
	Smiley(r'¿', _('slot machine'), r'¿'),
	Smiley(r'¿', _('hot springs'), r'¿'),
	Smiley(r'¿', _('moyai statue'), r'¿'),
	Smiley(r'¿', _('circus tent'), r'¿'),
	Smiley(r'¿', _('theater masks representing the performing arts'), r'¿'),
	Smiley(r'¿', _('round pushpin'), r'¿'),
	Smiley(r'¿', _('triangular flag on post'), r'¿'),
	Smiley(r'¿¿', _('japanese flag'), r'¿¿'),
	Smiley(r'¿¿', _('south korean flag'), r'¿¿'),
	Smiley(r'¿¿', _('german flag'), r'¿¿'),
	Smiley(r'¿¿', _('chinese flag'), r'¿¿'),
	Smiley(r'¿¿', _('united states flag'), r'¿¿'),
	Smiley(r'¿¿', _('french flag'), r'¿¿'),
	Smiley(r'¿¿', _('spanish flag'), r'¿¿'),
	Smiley(r'¿¿', _('italian flag'), r'¿¿'),
	Smiley(r'¿¿', _('russian flag'), r'¿¿'),
	Smiley(r'¿¿', _('united kingdom flag'), r'¿¿'),
	Smiley(r'¿', _('northeast arrow'), r'¿'),
	Smiley(r'¿', _('northwest arrow'), r'¿'),
	Smiley(r'¿', _('southeast arrow'), r'¿'),
	Smiley(r'¿', _('southwest arrow'), r'¿'),
	Smiley(r'¿', _('left right arrow'), r'¿'),
	Smiley(r'¿', _('up down arrow'), r'¿'),
	Smiley(r'¿', _('revolving arrows'), r'¿'),
	Smiley(r'¿', _('twisted right arrows representing media shuffle playback'), r'¿'),
	Smiley(r'¿', _('clockwise circle arrows representing media playback repeat'), r'¿'),
	Smiley(r'¿', _('clockwise circle arrows with circled number one representing media playback repeat of single track'), r'¿'),
	Smiley(r'¿', _('antenna with signal bars'), r'¿'),
	Smiley(r'¿', _('movie theater'), r'¿'),
	Smiley(r'¿', _('ideograph meaning reserved'), r'¿'),
	Smiley(r'¿', _('ideograph meaning empty and available'), r'¿'),
	Smiley(r'¿', _('ideograph meaning full capacity'), r'¿'),
	Smiley(r'¿', _('ideograph meaning agree or join together'), r'¿'),
	Smiley(r'¿', _('ideograph meaning prohibited or restricted'), r'¿'),
	Smiley(r'¿', _('ideograph meaning good bargain or prise'), r'¿'),
	Smiley(r'¿', _('ideograph meaning discount or sale'), r'¿'),
	Smiley(r'¿', _('ideograph meaning work or open for business'), r'¿'),
	Smiley(r'¿', _('ideograph meaning to own or possess'), r'¿'),
	Smiley(r'¿', _('ideograph meaning to lack or have none'), r'¿'),
	Smiley(r'¿', _('restroom'), r'¿'),
	Smiley(r'¿', _('mens symbol'), r'¿'),
	Smiley(r'¿', _('womens symbol'), r'¿'),
	Smiley(r'¿', _('baby symbol'), r'¿'),
	Smiley(r'¿', _('water closet'), r'¿'),
	Smiley(r'¿', _('potable water sign'), r'¿'),
	Smiley(r'¿', _('put litter in its place sign'), r'¿'),
	Smiley(r'¿', _('parking sign'), r'¿'),
	Smiley(r'¿', _('wheelchair symbol'), r'¿'),
	Smiley(r'¿', _('no smoking sign'), r'¿'),
	Smiley(r'¿', _('ideograph meaning month or moon'), r'¿'),
	Smiley(r'¿', _('ideograph meaning application form or monkey in chinese zodiac'), r'¿'),
	Smiley(r'¿', _('ideograph meaning service fee'), r'¿'),
	Smiley(r'¿', _('circled capital m'), r'¿'),
	Smiley(r'¿', _('passport control'), r'¿'),
	Smiley(r'¿', _('baggage claim'), r'¿'),
	Smiley(r'¿', _('left luggage'), r'¿'),
	Smiley(r'¿', _('customs'), r'¿'),
	Smiley(r'¿', _('ideograph meaning accepted'), r'¿'),
	Smiley(r'¿', _('ideograph meaning secret'), r'¿'),
	Smiley(r'¿', _('ideograph meaning congratulations'), r'¿'),
	Smiley(r'¿', _('clear button'), r'¿'),
	Smiley(r'¿', _('s o s sign'), r'¿'),
	Smiley(r'¿', _('identification sign'), r'¿'),
	Smiley(r'¿', _('restricted symbol'), r'¿'),
	Smiley(r'¿', _('no one under eighteen symbol'), r'¿'),
	Smiley(r'¿', _('no mobile phones symbol'), r'¿'),
	Smiley(r'¿', _('do not litter symbol'), r'¿'),
	Smiley(r'¿', _('non potable water sign'), r'¿'),
	Smiley(r'¿', _('no bicycles symbol'), r'¿'),
	Smiley(r'¿', _('no pedestrians symbol'), r'¿'),
	Smiley(r'¿', _('children crossing symbol'), r'¿'),
	Smiley(r'¿', _('no entry sign'), r'¿'),
	Smiley(r'¿', _('eight spoked asterisk'), r'¿'),
	Smiley(r'¿', _('sparkle'), r'¿'),
	Smiley(r'¿', _('heart decoration'), r'¿'),
	Smiley(r'¿', _('versus symbol'), r'¿'),
	Smiley(r'¿', _('vibration mode'), r'¿'),
	Smiley(r'¿', _('mobile phone off'), r'¿'),
	Smiley(r'¿', _('blood type ay symbol'), r'¿'),
	Smiley(r'¿', _('blood type b symbol'), r'¿'),
	Smiley(r'¿', _('blood type ay b symbol'), r'¿'),
	Smiley(r'¿', _('blood type o symbol'), r'¿'),
	Smiley(r'¿', _('universal recycling symbol'), r'¿'),
	Smiley(r'¿', _('aries astrological sign'), r'¿'),
	Smiley(r'¿', _('taurus astrological sign'), r'¿'),
	Smiley(r'¿', _('gemini astrological sign'), r'¿'),
	Smiley(r'¿', _('cancer astrological sign'), r'¿'),
	Smiley(r'¿', _('leo astrological sign'), r'¿'),
	Smiley(r'¿', _('virgo astrological sign'), r'¿'),
	Smiley(r'¿', _('libra astrological sign'), r'¿'),
	Smiley(r'¿', _('scorpio astrological sign'), r'¿'),
	Smiley(r'¿', _('sagittarius astrological sign'), r'¿'),
	Smiley(r'¿', _('Capricorn astrological sign'), r'¿'),
	Smiley(r'¿', _('Aquarius astrological sign'), r'¿'),
	Smiley(r'¿', _('pisces astrological sign'), r'¿'),
	Smiley(r'¿', _('Ophiuchus astrological sign'), r'¿'),
	Smiley(r'¿', _('six pointed star with dot in middle'), r'¿'),
	Smiley(r'¿', _('ay t m'), r'¿'),
	Smiley(r'¿', _('heavy dollar sign'), r'¿'),
	Smiley(r'¿', _('currency exchange'), r'¿'),
	Smiley(r'¿', _('top symbol'), r'¿'),
	Smiley(r'¿', _('end symbol'), r'¿'),
	Smiley(r'¿', _('back symbol'), r'¿'),
	Smiley(r'¿', _('on symbol'), r'¿'),
	Smiley(r'¿', _('soon symbol'), r'¿'),
	Smiley(r'¿', _('red cross mark'), r'¿'),
	Smiley(r'¿', _('red circle'), r'¿'),
	Smiley(r'¿', _('red exclamation mark'), r'¿'),
	Smiley(r'¿', _('black question mark'), r'¿'),
	Smiley(r'¿', _('white exclamation mark'), r'¿'),
	Smiley(r'¿', _('white question mark'), r'¿'),
	Smiley(r'¿', _('clock face showing twelve a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing twelve thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing one a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing one thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing two a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing two thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing three a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing three thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing four a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing four thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing five a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing five thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing six a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing seven a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing eight a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing nine a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing ten a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing eleven a clock'), r'¿'),
	Smiley(r'¿', _('clock face showing six thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing seven thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing eight thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing nine thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing ten thirty'), r'¿'),
	Smiley(r'¿', _('clock face showing eleven thirty'), r'¿'),
	Smiley(r'¿', _('spade suit'), r'¿'),
	Smiley(r'¿', _('heart suit'), r'¿'),
	Smiley(r'¿', _('club suit'), r'¿'),
	Smiley(r'¿', _('diamond suit'), r'¿'),
	Smiley(r'¿', _('white flower with text meaning well done'), r'¿'),
	Smiley(r'¿', _('curly loop'), r'¿'),
	Smiley(r'¿', _('trident emblem'), r'¿'),
	Smiley(r'¿', _('apple"'), r'¿'),
]

def terminate(self):
	global emoticons
	del emoticons
